[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.10.0"

[[constraint]]
  name = "github.com/Clever/configure"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
