package main

import (
	"io"
	"strings"

	. "github.com/dave/jennifer/jen"
	"github.com/go-yaml/yaml"
)

type envVar struct {
	Name string `yaml:"name"`
}

// ValuesYML Schema
type ValuesYML struct {
	Env              []envVar `yaml:"env"`
	Secrets          []envVar `yaml:"secrets"`
	Dependencies     []string `yaml:"dependencies"`
	ExternalUrlUsage []string `yaml:"externalUrlUsage"`
}

// toEnvVarName mirrors the chart's regexReplaceAll "[^A-Z0-9]" (upper $url) "_"
func toEnvVarName(s string) string {
	upper := strings.ToUpper(s)
	return strings.Map(func(r rune) rune {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			return r
		}
		return '_'
	}, upper)
}

func generateKubernetes(packageName string, skipDependencies map[string]bool, overrideDependenciesString string, data []byte, output io.Writer) error {
	t := ValuesYML{}
	if err := yaml.Unmarshal(data, &t); err != nil {
		return err
	}

	f := NewFile(packageName)
	f.HeaderComment("Code generated by launch-gen DO NOT EDIT.")

	f.Comment("LaunchConfig is auto-generated based on the values YAML file")
	f.Type().Id("LaunchConfig").Struct(
		Id("Deps").Id("Dependencies"),
		Id("Env").Id("Environment"),
		Id("ExternalUrlUsage"),
	)

	overrideDependenciesMap := parseOverrideDependencies(&overrideDependenciesString, t.Dependencies)
	depsInitDict, depInitLines := generateDependencies(f, t.Dependencies, skipDependencies, overrideDependenciesMap)
	envInitDict := generateEnvironment(f, t.Env, t.Secrets)
	externalUrlInitDict := generateExternalUrlUsage(f, t.ExternalUrlUsage)

	lines := append(depInitLines, Return(Id("LaunchConfig").Values(Dict{
		Id("Deps"):             Id("Dependencies").Values(depsInitDict),
		Id("Env"):              Id("Environment").Values(envInitDict),
		Id("ExternalUrlUsage"): Id("ExternalUrlUsage").Values(externalUrlInitDict),
	})))

	f.Comment("InitLaunchConfig creates a LaunchConfig")
	initLaunchConfigParams := []Code{Id("exp *").Qual("go.opentelemetry.io/otel/sdk/trace", "SpanExporter")}
	f.Func().Id("InitLaunchConfig").Params(initLaunchConfigParams...).Id("LaunchConfig").Block(lines...)

	emitRequireEnvVar(f)

	return f.Render(output)
}

func generateEnvironment(f *File, env []envVar, secrets []envVar) Dict {
	optionalEnvVars := []string{
		// Not used in dev
		"TRACING_ACCESS_TOKEN",
	}
	envStruct := []Code{}
	envInitDict := Dict{}
	for _, v := range append(env, secrets...) {
		envStruct = append(envStruct, List(Id(toPublicVar(v.Name))).String())
		if contains(optionalEnvVars, v.Name) {
			envInitDict[Id(toPublicVar(v.Name))] = Id("os.Getenv").Call(Lit(v.Name))
		} else {
			envInitDict[Id(toPublicVar(v.Name))] = Id("requireEnvVar").Call(Lit(v.Name))
		}
	}
	f.Type().Id("Environment").Struct(envStruct...)
	return envInitDict
}

func generateExternalUrlUsage(f *File, urls []string) Dict {
	externalUrlStruct := []Code{}
	externalUrlInitDict := Dict{}
	for _, s := range urls {
		externalUrlStruct = append(externalUrlStruct, List(Id(toPublicVar(s))).String())
		externalUrlInitDict[Id(toPublicVar(s))] = Id("requireEnvVar").Call(Lit("EXTERNAL_URL_" + toEnvVarName(s)))
	}
	f.Type().Id("ExternalUrlUsage").Struct(externalUrlStruct...)
	return externalUrlInitDict
}
