package main

import (
	"flag"
	"io/ioutil"
	"log"
	"os"
	"sort"

	. "github.com/dave/jennifer/jen"
	"github.com/go-yaml/yaml"
)

// LaunchYML Schema
type LaunchYML struct {
	Env              []string `yaml:"env"`
	Dependencies     []string `yaml:"dependencies"`
	ExternalUrlUsage []string `yaml:"externalUrlUsage"`
	Aws              struct {
		S3 struct {
			Read  []string `json:"read"`
			Write []string `json:"write"`
		} `json:"s3"`
	} `json:"aws"`
}

const (
	funcGetS3NameByEnv = "getS3NameByEnv"
)

func sortedKeys(m map[string]struct{}) []string {
	keys := []string{}
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func main() {
	t := LaunchYML{}
	packageName := flag.String("p", "main", "optional package name")
	outputFile := flag.String("o", "", "optional output to file. Default is stdout")
	skipDependencies := map[string]bool{}
	flag.Func("skip-dependency", "Dependency to skip generating wag clients. Can be added multiple times e.g. -skip-dependency a -skip-dependency b", func(s string) error {
		skipDependencies[s] = true
		return nil
	})
	overrideDependenciesString := flag.String("d", "", "Dependency name to override. You can provide multiple dependencies in the format dep1:replacementDep1,dep2:replacementDep2,...")
	flag.Parse()

	if len(flag.Args()) < 1 {
		log.Fatal("usage: launch-gen [-p <package_name>] <file>")
	}

	output := os.Stdout
	if *outputFile != "" {
		f, err := os.Create(*outputFile)
		if err != nil {
			log.Fatalf("error opening file '%s': %s", *outputFile, err)
		}
		defer f.Close()
		output = f
	}

	data, err := ioutil.ReadFile(flag.Args()[0])
	if err != nil {
		log.Fatalf("error: %v", err)
	}

	err = yaml.Unmarshal([]byte(data), &t)
	if err != nil {
		log.Fatalf("error: %v", err)
	}

	f := NewFile(*packageName)
	f.Comment("Code generated by launch-gen DO NOT EDIT.")
	f.Id("")

	f.Comment("LaunchConfig is auto-generated based on the launch YML file")
	f.Type().Id("LaunchConfig").Struct(
		Id("Deps").Id("Dependencies"),
		Id("Env").Id("Environment"),
		Id("AwsResources"),
		Id("ExternalUrlUsage"),
	)

	// parseOverrideDependencies parses the list of dependencies to be overwritten into a map
	overrideDependenciesMap := parseOverrideDependencies(overrideDependenciesString, t.Dependencies)

	// Dependencies
	depsInitDict, depInitLines := generateDependencies(f, t.Dependencies, skipDependencies, overrideDependenciesMap)

	// Environment
	envStruct := []Code{}
	envInitDict := Dict{}
	optionalEnvVars := []string{
		// Not used in dev
		"TRACING_ACCESS_TOKEN",
	}
	for _, s := range t.Env {
		envStruct = append(envStruct, List(Id(toPublicVar(s))).String())
		if contains(optionalEnvVars, s) {
			envInitDict[Id(toPublicVar(s))] = Id("os.Getenv").Call(Lit(s))
		} else {
			envInitDict[Id(toPublicVar(s))] = Id("requireEnvVar").Call(Lit(s))
		}
	}

	f.Comment("Environment has environment variables and their values")
	f.Type().Id("Environment").Struct(envStruct...)

	// AWS Resources
	awsStruct := []Code{}
	awsInitDict := Dict{}

	s3Buckets := map[string]struct{}{}
	for _, bucket := range t.Aws.S3.Read {
		s3Buckets[bucket] = struct{}{}
	}
	for _, bucket := range t.Aws.S3.Write {
		s3Buckets[bucket] = struct{}{}
	}

	for _, a := range sortedKeys(s3Buckets) {
		name := "S3" + toPublicVar(a)
		awsStruct = append(awsStruct, List(Id(name)).String())
		awsInitDict[Id(name)] = Id(funcGetS3NameByEnv).Call(Lit(a))
	}

	f.Comment("AwsResources contains string IDs that will help for accessing various AWS resources")
	f.Type().Id("AwsResources").Struct(awsStruct...)

	// External URL usage
	externalUrlStruct := []Code{}
	externalUrlInitDict := Dict{}
	for _, s := range t.ExternalUrlUsage {
		externalUrlStruct = append(externalUrlStruct, List(Id(toPublicVar(s))).String())
		externalUrlInitDict[Id(toPublicVar(s))] = Id(toPrivateVar(s))
	}

	f.Comment("ExternalUrlUsage uses discovery to generate urls for external services")
	f.Type().Id("ExternalUrlUsage").Struct(externalUrlStruct...)

	////////////////////
	// InitLaunchConfig() function
	////////////////////
	lines := depInitLines

	// setup external url discovery for each dependency
	for _, s := range t.ExternalUrlUsage {
		c := []Code{
			List(Id(toPrivateVar(s)), Err()).Op(":=").
				Qual("github.com/Clever/discovery-go", "ExternalURL").
				Call(Lit(s)),
			If(Err().Op("!=").Nil()).Block(
				Qual("log", "Fatalf").Call(List(Lit("discovery error: %s"), Err())),
			),
		}

		lines = append(lines, c...)
	}

	// Return the full launch Config
	ret := Return(Id("LaunchConfig").Values(Dict{
		Id("Deps"):             Id("Dependencies").Values(depsInitDict),
		Id("Env"):              Id("Environment").Values(envInitDict),
		Id("AwsResources"):     Id("AwsResources").Values(awsInitDict),
		Id("ExternalUrlUsage"): Id("ExternalUrlUsage").Values(externalUrlInitDict),
	}))

	lines = append(lines, ret)

	f.Comment("InitLaunchConfig creates a LaunchConfig")
	initLaunchConfigParams := []Code{Id("exp *").Qual("go.opentelemetry.io/otel/sdk/trace", "SpanExporter")}

	f.Func().Id("InitLaunchConfig").Params(initLaunchConfigParams...).Id("LaunchConfig").Block(lines...)

	emitRequireEnvVar(f)

	f.Comment(`getS3NameByEnv adds "-dev" to an env var name unless we're in "production" deploy env, and appends _POD_ACCOUNT if the account is in podAccountSuffixMap`)
	f.Comment(`We check both DEPLOY_ENV and _DEPLOY_ENV env vars, which are injected by our deployment system for Lambda and non-Lambda deployments, respectively`)
	f.Func().Id(funcGetS3NameByEnv).Params(Id("s").String()).String().Block(
		Id("env").Op(":=").Qual("os", "Getenv").Call(Lit("DEPLOY_ENV")),
		If(Id("env").Op("==").Lit("")).Block(
			Id("env").Op("=").Qual("os", "Getenv").Call(Lit("_DEPLOY_ENV")),
		),
		If(Id("env").Op("==").Lit("")).Block(
			Qual("log", "Fatal").Call(List(Lit("Unable to determine deployment environment (DEPLOY_ENV and _DEPLOY_ENV are undefined)"))),
		),
		If(Id("env").Op("==").Lit("production")).Block(
			Return(Id("s")),
		),
		Id("podAccount").Op(":=").Qual("os", "Getenv").Call(Lit("_POD_ACCOUNT")),
		If(Id("podAccount").Op("!=").Lit("").Op("&&").Id("podAccountSuffixMap").Index(Id("podAccount"))).Block(
			Return(Id("s").Op("+").Lit("-dev-").Op("+").Id("podAccount")),
		),
		Return(Id("s").Op("+").Lit("-dev")),
	)

	// Generate podAccountMap with the configured accounts (not user-configurable)
	mapValues := Dict{}
	for account := range podAccountSuffixMap {
		mapValues[Lit(account)] = True()
	}
	f.Var().Id("podAccountSuffixMap").Op("=").Map(String()).Bool().Values(mapValues)

	err = f.Render(output)
	if err != nil {
		panic(err)
	}
}

var podAccountSuffixMap = map[string]bool{
	"585008086734": true, // dev workload account
}
