version: 2.1
orbs:
  clever: clever/circleci-orbs@0

workflows:
  build_test_publish:
    jobs:
      - clever/go_test:
          context:
            - github-app-auth
      - clever/go_lint:
          context:
            - github-app-auth
      - clever/publish_utility:
          requires:
            - clever/go_test
            - clever/go_lint
          filters:
            branches:
              only: master
          context:
            - aws-lambda-private
            - aws-ecr-private
